package errorcode

/////////////////////////////
////    API錯誤代碼
/////////////////////////////

type ErrorCode string

// api錯誤代碼
const (
	Success                 ErrorCode = "0"
	InsufficientBalance     ErrorCode = "1"
	PlayerNoFound           ErrorCode = "2"
	BetNotAllowed           ErrorCode = "3"
	TokenInvalid            ErrorCode = "4"
	AuthorizationInvalid    ErrorCode = "5"
	FrozenPlayer            ErrorCode = "6"
	BadParameters           ErrorCode = "7"
	GameInvalid             ErrorCode = "8"
	InvalidGameToken        ErrorCode = "9"
	InvalidRound            ErrorCode = "10"
	InvalidMTCode           ErrorCode = "11"
	CancelBet               ErrorCode = "12"
	RolloutExist            ErrorCode = "13"
	RollinExist             ErrorCode = "14"
	RoundEnded              ErrorCode = "15"
	DataNoFound             ErrorCode = "16"
	RefundNotAllowed        ErrorCode = "17"
	AlreadyRefunded         ErrorCode = "18"
	GameTeamInvalid         ErrorCode = "19"
	GameCodeDuplicate       ErrorCode = "20"
	DuplicateGameRegistered ErrorCode = "21"
	ToDateMustEarlier       ErrorCode = "22"
	WalletRecoverFailed     ErrorCode = "23"
	RecoverFailed           ErrorCode = "24"
	FailedLogCompairError   ErrorCode = "25"
	DuplicateRecord         ErrorCode = "26"
	DuplicateOrder          ErrorCode = "27"
	ConnectServiceError     ErrorCode = "29"
	IllegalOpetation        ErrorCode = "30"
	OrderExists             ErrorCode = "31"
	IndexNoFound            ErrorCode = "32"
	RecordNoFound           ErrorCode = "33"
	OrderNoFound            ErrorCode = "34"
	AmendLogNoFound         ErrorCode = "35"
	FailedLogNoFound        ErrorCode = "36"
	DuplicateAmends         ErrorCode = "37"
	NotRefundYet            ErrorCode = "38"
	GenreInvalid            ErrorCode = "39"
	DoubleRefunded          ErrorCode = "40"
	TimeFormatError         ErrorCode = "41"
	NoPastTime              ErrorCode = "42"
	RolloutNoFound          ErrorCode = "43"
	CurrencyNotMatch        ErrorCode = "44"
	FlowError               ErrorCode = "45"
	IndexStatusInvalid      ErrorCode = "46"
	DuplicateRequest        ErrorCode = "47"
	WalletServerError       ErrorCode = "49"
	RefundFailed            ErrorCode = "50"
	RefundFailed1           ErrorCode = "51"
	RefundFailed2           ErrorCode = "52"
	TransactioneRefundError ErrorCode = "53"
	OrderClosed             ErrorCode = "55"
	TokenNoFound            ErrorCode = "56"
	AgentWalletInsufficient ErrorCode = "57"
	WalletBetNoFound        ErrorCode = "62"
	RepeatedCancelOrRefund  ErrorCode = "63"
	SomethingWrong          ErrorCode = "100"
	GetBalanceFailed        ErrorCode = "101"
	AuthServiceError        ErrorCode = "102"
	OrderServiceError       ErrorCode = "103"
	TransactionServiceError ErrorCode = "104"
	AuthModuleError         ErrorCode = "105"
	OrderModuleError        ErrorCode = "106"
	TransactionModuleError  ErrorCode = "107"
	RedisError              ErrorCode = "108"
	MongodbError            ErrorCode = "109"
	OrderviewerServiceError ErrorCode = "110"
	OrderviewerModuleError  ErrorCode = "111"
	GameManagerServiceError ErrorCode = "112"
	GameManagerModuleError  ErrorCode = "113"
	TooManyBets             ErrorCode = "114"
	CobrandServiceError     ErrorCode = "115"
	KillRateServiceError    ErrorCode = "116"
	KillRateModuleError     ErrorCode = "117"
	BetNotYet               ErrorCode = "118"
	OrderlottoServiceError  ErrorCode = "119"
	UserModuleError         ErrorCode = "120"
	UserServiceError        ErrorCode = "121"
	LottoviewerServiceError ErrorCode = "122"
	LottoviewerModuleError  ErrorCode = "123"
	PromotionServiceError   ErrorCode = "124"
	PromotionModuleError    ErrorCode = "125"
	OrderlottoModuleError   ErrorCode = "126"
	LockError               ErrorCode = "6969"
)
