definitions:
  backgroundmanager_handler.AllGameDataStatisticalResponse:
    properties:
      Count:
        description: 資料筆數
        type: integer
      Data:
        description: 資料給予的地方
        items:
          $ref: '#/definitions/backgroundmanager_handler.AllGameDataStatisticalResponseData'
        type: array
      Status:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.BackendHttpResponseStatus'
        description: 狀態
    type: object
  backgroundmanager_handler.AllGameDataStatisticalResponseData:
    properties:
      Bet:
        description: 下注
        type: number
      GameCode:
        description: 遊戲代碼
        type: string
      GameName:
        description: 遊戲名稱
        type: string
      Payout:
        description: 派彩
        type: number
      WinLose:
        description: 輸贏
        type: number
    type: object
  backgroundmanager_handler.BackendHttpResponseStatus:
    properties:
      Code:
        description: 狀態碼
        type: string
      Message:
        description: 訊息
        type: string
      Timestamp:
        description: 時間戳
        type: integer
    type: object
  backgroundmanager_handler.BackendReportDetail:
    properties:
      bet:
        description: 下注
        type: number
      count:
        description: 筆數
        type: integer
      date:
        description: 日期
        type: string
      gameCode:
        description: 遊戲代碼
        type: string
      gameName:
        description: 遊戲名稱
        type: string
      gameTeam:
        description: 團隊
        type: string
      income:
        description: 收入
        type: number
      jackpot:
        description: 彩池
        type: integer
      rake:
        description: 抽水
        type: integer
      rtp:
        description: RTP
        type: number
      win:
        description: 贏分
        type: number
    type: object
  backgroundmanager_handler.BackendReportRequestBody:
    properties:
      EndTime:
        default: "2023-07-02T00:00:00.000Z"
        description: EndTime,UTC
        type: string
      StartTime:
        default: "2023-07-01T00:00:00.000Z"
        description: StartTime,UTC
        type: string
      Token:
        default: 258EAFA5-E914-47DA-95CA-C5AB0DC85B11
        description: Token
        type: string
    type: object
  backgroundmanager_handler.BackendReportResponse:
    properties:
      data:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.BackendReportResponseBody'
        description: 資料
      status:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.MaHttpResponseStatus'
        description: 狀態欄
    type: object
  backgroundmanager_handler.BackendReportResponseBody:
    properties:
      list:
        description: 列表
        items:
          $ref: '#/definitions/backgroundmanager_handler.BackendReportDetail'
        type: array
      totalBet:
        description: 總下注
        type: number
      totalIncome:
        description: 總收入
        type: number
      totalJackpot:
        description: 總彩池
        type: number
      totalRake:
        description: 總抽水
        type: number
      totalRtp:
        description: 總RTP
        type: number
      totalSize:
        description: 總筆數
        type: integer
      totalWin:
        description: 總贏分
        type: number
    type: object
  backgroundmanager_handler.BetSlipDetailsResponse:
    properties:
      Data:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.BetSlipDetailsResponseData'
        description: 資料給予的地方
      Status:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.BackendHttpResponseStatus'
        description: 狀態
    type: object
  backgroundmanager_handler.BetSlipDetailsResponseData:
    properties:
      Currency:
        description: 幣別
        type: string
      EndTime:
        description: 成單時間
        type: string
      GameCode:
        description: 遊戲代碼
        type: string
      GameLog:
        description: 遊戲log
        items:
          type: integer
        type: array
      GameName:
        description: 遊戲名稱
        type: string
      GameResult:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.GameResultDetailList'
        description: 遊戲結果
      MemberAccount:
        description: 對方會員帳號
        type: string
      OwnerID:
        description: 總代理編號
        type: string
      Paccount:
        description: 代理帳號
        type: string
      ParentID:
        description: 代理編號
        type: string
      PlatformMemberID:
        description: 對方會員編號
        type: string
      RoundID:
        description: 局號
        type: string
      StatusID:
        description: "狀態碼\t0(正常)、1(會員不存在)、2(交易失敗)、3(寫賽果失敗)、4(寫log失敗)"
        type: integer
    type: object
  backgroundmanager_handler.BetSlipInfoResponse:
    properties:
      Data:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.BetSlipInfoResponseData'
        description: 資料給予的地方
      Status:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.BackendHttpResponseStatus'
        description: 狀態
    type: object
  backgroundmanager_handler.BetSlipInfoResponseData:
    properties:
      account:
        description: 玩家帳號  ※字串長度限制36個字元
        type: string
      gameCode:
        description: 遊戲代碼
        type: string
      gametype:
        description: 遊戲類別
        type: string
      id:
        description: 玩家編號
        type: string
      paccount:
        description: 代理帳號 (會由我方依據要求方來源判斷此欄位要不要有值，若無值則不用顯示)
        type: string
      roundid:
        description: Round ID
        type: string
    type: object
  backgroundmanager_handler.BetSlipListResponse:
    properties:
      Count:
        description: 資料筆數
        type: integer
      Data:
        description: 資料給予的地方
        items:
          $ref: '#/definitions/backgroundmanager_handler.BetSlipListResponseData'
        type: array
      Status:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.BackendHttpResponseStatus'
        description: 狀態
    type: object
  backgroundmanager_handler.BetSlipListResponseData:
    properties:
      Bet:
        description: 下注
        type: number
      BetTime:
        description: 下注時間
        type: string
      EndTime:
        description: 結算時間
        type: string
      GameCode:
        description: 遊戲代碼
        type: string
      GameName:
        description: 遊戲名稱
        type: string
      MemberAccount:
        description: 對方會員帳號
        type: string
      Payout:
        description: 派彩
        type: number
      PayoutTime:
        description: 派彩時間
        type: string
      PlatformMemberID:
        description: 對方會員編號
        type: string
      RoundID:
        description: 局號
        type: string
      StatusID:
        description: "狀態碼\t0 正常\t1 會員不存在\t2 交易失敗\t3 寫賽果失敗\t4 寫log失敗"
        type: integer
      WinLose:
        description: 輸贏
        type: number
    type: object
  backgroundmanager_handler.ChangeTimeZoneRequestBody:
    properties:
      TimeSpan:
        default: "+08:00"
        description: 時區
        type: string
    type: object
  backgroundmanager_handler.ChangeTimeZoneResponse:
    properties:
      AvatarPath:
        description: 頭像路徑
        type: string
      Status:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.BackendHttpResponseStatus'
        description: 狀態
      access_token:
        description: 訪問令牌
        type: string
    type: object
  backgroundmanager_handler.GameResultDetail:
    properties:
      Action:
        description: 動作
        type: string
      Amount:
        description: 金額
        type: number
      Time:
        description: 時間
        type: string
    type: object
  backgroundmanager_handler.GameResultDetailList:
    properties:
      GameResultDetails:
        description: 賽果詳情
        items:
          $ref: '#/definitions/backgroundmanager_handler.GameResultDetail'
        type: array
    type: object
  backgroundmanager_handler.MaHttpResponseStatus:
    properties:
      code:
        description: 狀態碼
        type: string
      dateTime:
        description: 回應時間
        type: string
      latency:
        description: latency
        type: string
      message:
        description: 狀態訊息
        type: string
      tracecode:
        description: 追蹤碼
        type: string
      wallettype:
        description: 錢包類別transfer=轉帳錢包，single=單一錢包，ce=虛擬幣錢包
        type: string
    type: object
  backgroundmanager_handler.MemberListResponse:
    properties:
      Count:
        description: 資料筆數
        type: integer
      Data:
        description: 資料給予的地方
        items:
          $ref: '#/definitions/backgroundmanager_handler.MemberListResponseData'
        type: array
      Status:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.BackendHttpResponseStatus'
        description: 狀態
    type: object
  backgroundmanager_handler.MemberListResponseData:
    properties:
      Balance:
        description: 玩家餘額
        type: number
      Currency:
        description: 玩家幣別
        type: string
      MemberAccount:
        description: 我方會員編號
        type: string
      MemberID:
        description: 我方會員編號
        type: integer
      NewPoolID:
        description: 下次使用池編號
        type: integer
      PoolID:
        description: 使用中池編號
        type: integer
      RTP:
        description: RTP
        type: number
    type: object
  backgroundmanager_handler.SignInRequestBody:
    properties:
      Account:
        default: admin
        description: 會員帳號
        type: string
      Browser:
        default: chrome
        description: 登入瀏覽器
        type: string
      Device:
        default: Win-PC
        description: 登入設備
        type: string
      Password:
        default: chimera@888
        description: 會員密碼
        type: string
      TimeSpan:
        default: "+08:00"
        description: 時區
        type: string
    type: object
  backgroundmanager_handler.SignInResponse:
    properties:
      Authority:
        description: 權限
        type: integer
      AvatarPath:
        description: 頭像路徑
        type: string
      Status:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.BackendHttpResponseStatus'
        description: 狀態
      access_token:
        description: 訪問令牌
        type: string
      refresh_token:
        description: 刷新令牌
        type: string
    type: object
  backgroundmanager_handler.SignOutResponse:
    properties:
      Status:
        allOf:
        - $ref: '#/definitions/backgroundmanager_handler.BackendHttpResponseStatus'
        description: 狀態
    type: object
info:
  contact: {}
paths:
  /Api/BetSlipInfo:
    get:
      consumes:
      - application/json
      parameters:
      - description: Token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backgroundmanager_handler.BetSlipInfoResponse'
      security:
      - Bearer: []
      summary: 取得注單資訊
      tags:
      - 注單資訊
  /BetSlip/BetSlipDetails:
    get:
      consumes:
      - application/json
      parameters:
      - default: CCVY1h5pfvunb000694
        description: 局號
        in: query
        name: RoundID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backgroundmanager_handler.BetSlipDetailsResponse'
      security:
      - Bearer: []
      summary: 注單詳情
      tags:
      - 注單
  /BetSlip/BetSlipList:
    get:
      consumes:
      - application/json
      parameters:
      - description: 會員編號
        in: query
        name: MemberID
        type: integer
      - description: 局號
        in: query
        name: RoundID
        type: string
      - default: "2023-07-01 00:00:00"
        description: 開始時間
        in: query
        name: sDate
        required: true
        type: string
      - default: "2023-07-24 23:59:59"
        description: 結束時間
        in: query
        name: eDate
        required: true
        type: string
      - default: "0"
        description: 跳過筆數
        in: query
        name: Skip
        required: true
        type: string
      - default: "10"
        description: 顯示筆數
        in: query
        name: Show
        required: true
        type: string
      - default: MemberAccount
        description: 排序欄位
        in: query
        name: Field
        required: true
        type: string
      - default: desc
        description: 排序類型 asc(小->大)、desc(大->小)
        in: query
        name: OrderType
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backgroundmanager_handler.BetSlipListResponse'
      security:
      - Bearer: []
      summary: 注單列表
      tags:
      - 注單
  /GameReport/AllGameDataStatistical:
    get:
      consumes:
      - application/json
      parameters:
      - default: "2023-07-01 00:00:00"
        description: 開始時間
        in: query
        name: sDate
        required: true
        type: string
      - default: "2023-07-24 00:00:00"
        description: 結束時間
        in: query
        name: eDate
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backgroundmanager_handler.AllGameDataStatisticalResponse'
      security:
      - Bearer: []
      summary: 遊戲綜合統計
      tags:
      - 遊戲統計
  /Member/MemberList:
    get:
      consumes:
      - application/json
      parameters:
      - description: 會員編號
        in: query
        name: MemberID
        type: integer
      - default: "0"
        description: 跳過筆數
        in: query
        name: Skip
        required: true
        type: string
      - default: "10"
        description: 顯示筆數
        in: query
        name: Show
        required: true
        type: string
      - default: MemberAccount
        description: 排序欄位
        in: query
        name: Field
        required: true
        type: string
      - default: desc
        description: 排序類型 asc(小->大)、desc(大->小)
        in: query
        name: OrderType
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backgroundmanager_handler.MemberListResponse'
      security:
      - Bearer: []
      summary: 取得會員列表
      tags:
      - 會員
  /Token/ChangeTimeZone:
    post:
      consumes:
      - application/json
      parameters:
      - description: RequestBody
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/backgroundmanager_handler.ChangeTimeZoneRequestBody'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backgroundmanager_handler.ChangeTimeZoneResponse'
      security:
      - Bearer: []
      summary: 變更時區
      tags:
      - 登入授權令牌、換發
  /Token/SignIn:
    post:
      consumes:
      - application/json
      parameters:
      - description: RequestBody
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/backgroundmanager_handler.SignInRequestBody'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backgroundmanager_handler.SignInResponse'
      security:
      - Bearer: []
      summary: 會員登入
      tags:
      - 登入授權令牌、換發
  /backend/report:
    post:
      consumes:
      - application/json
      parameters:
      - description: RequestBody
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/backgroundmanager_handler.BackendReportRequestBody'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backgroundmanager_handler.BackendReportResponse'
      security:
      - Bearer: []
      summary: 取得後台報表
      tags:
      - 報表
  /token/SignOut:
    get:
      consumes:
      - application/json
      parameters:
      - description: 訪問令牌
        in: query
        name: access_token
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backgroundmanager_handler.SignOutResponse'
      security:
      - Bearer: []
      summary: 會員登出
      tags:
      - 登入授權令牌、換發
securityDefinitions:
  Bearer:
    description: 輸入Bearer {jwtToken}
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
